name: flutter_coffeeshop_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  provider: ^6.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/images/beans.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
